class Role:
    CUSTOMER = 'CUSTOMER'
    POLICY_AGENT = 'POLICY_AGENT'
    CLAIM_OFFICER = 'CLAIM_OFFICER'
    ADMIN = 'ADMIN'

class PolicyStatus:
    PENDING_APPROVAL = 'PENDING_APPROVAL'
    ACTIVE = 'ACTIVE'
    EXPIRED = 'EXPIRED'
    CANCELLED = 'CANCELLED'
    REJECTED = 'REJECTED'

class ClaimStatus:
    PENDING_ASSIGNMENT = 'PENDING_ASSIGNMENT'
    UNDER_REVIEW = 'UNDER_REVIEW'
    NEEDS_UPDATE = 'NEEDS_UPDATE'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'

class ReactivationStatus:
    PENDING = 'PENDING'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'

class ClaimAction:
    ASSIGNED = 'ASSIGNED'
    APPROVED = 'APPROVED'
    REJECTED = 'REJECTED'
    REQUESTED_UPDATE = 'REQUESTED_UPDATE'
    CUSTOMER_UPDATED = 'CUSTOMER_UPDATED'
